# Generated by Django 4.2.5 on 2024-04-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_category_recipe_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('NONE', 'None'), ('HEALTH_DIET', 'Health & Diet'), ('HOLIDAYS', 'Holidays')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_time',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert')], max_length=100),
        ),
    ]
